<a href="https://colab.research.google.com/github/gayatri-2005/Machine-Learning-/blob/main/Logistic_Regression_For_Multi_Class_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_classification

In [7]:
X,y = make_classification(n_samples=1000, n_features=20,n_informative=3,n_classes = 3,random_state=42)

In [8]:
X

array([[ 1.99615232,  0.21092616,  1.10317394, ...,  0.21486471,
         1.40220959,  1.00876251],
       [ 0.60073302,  0.14197991,  0.60826717, ...,  1.28920305,
         1.31060591, -1.48460479],
       [-1.97208903, -1.44392555, -0.94140317, ...,  1.49545825,
         0.84958453,  0.41156572],
       ...,
       [-0.96539616, -0.76548122,  1.89557477, ...,  1.37652266,
        -0.26382823,  0.17289168],
       [-0.63858583,  0.62308735, -0.99844085, ..., -2.15373057,
         0.97571338,  0.48630999],
       [ 0.62294403, -0.78703628,  0.23987275, ..., -1.07772075,
        -0.44664305, -0.50663483]])

In [9]:
y

array([2, 1, 0, 1, 1, 2, 0, 1, 2, 0, 1, 2, 0, 0, 0, 2, 0, 0, 1, 1, 2, 1,
       0, 1, 1, 1, 0, 2, 1, 1, 0, 0, 1, 0, 1, 0, 2, 2, 0, 2, 0, 0, 0, 1,
       2, 2, 1, 2, 1, 2, 0, 0, 1, 2, 2, 1, 0, 2, 2, 1, 0, 0, 1, 2, 2, 0,
       2, 2, 1, 2, 2, 2, 1, 2, 1, 0, 1, 1, 2, 1, 1, 0, 1, 2, 2, 1, 2, 1,
       1, 2, 2, 2, 2, 2, 2, 0, 0, 2, 1, 1, 1, 0, 1, 1, 1, 2, 2, 0, 0, 0,
       0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 1, 2, 1, 0, 2, 1, 0, 2, 1, 0, 1, 0,
       1, 2, 2, 0, 0, 1, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 1, 1, 2,
       0, 0, 1, 0, 0, 2, 2, 2, 0, 0, 2, 1, 2, 1, 1, 1, 2, 2, 0, 0, 2, 0,
       1, 0, 1, 2, 2, 2, 2, 1, 0, 0, 2, 2, 0, 1, 0, 1, 0, 1, 2, 1, 2, 0,
       0, 2, 2, 1, 1, 0, 1, 0, 1, 0, 1, 2, 1, 1, 0, 2, 0, 2, 1, 0, 2, 2,
       2, 0, 0, 1, 1, 2, 1, 1, 1, 0, 0, 2, 0, 1, 2, 1, 1, 1, 1, 0, 0, 2,
       2, 0, 2, 0, 0, 2, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 2, 1, 1, 1, 1, 1,
       2, 2, 0, 2, 2, 0, 1, 0, 2, 0, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 2, 0,
       2, 0, 0, 1, 1, 0, 1, 1, 1, 2, 0, 0, 0, 0, 1,

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)


In [13]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(multi_class='ovr')
lr.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [15]:
y_pred = lr.predict(X_test)
y_pred

array([0, 0, 0, 0, 2, 0, 2, 2, 2, 1, 0, 2, 1, 2, 2, 2, 2, 0, 2, 2, 0, 2,
       2, 2, 0, 1, 1, 1, 0, 1, 0, 1, 2, 0, 0, 1, 2, 0, 2, 0, 2, 0, 0, 1,
       0, 0, 0, 2, 1, 2, 1, 0, 2, 1, 1, 0, 0, 0, 0, 0, 0, 2, 1, 2, 0, 2,
       2, 0, 2, 2, 0, 2, 2, 0, 0, 1, 2, 2, 0, 2, 2, 2, 0, 1, 0, 1, 0, 1,
       2, 0, 2, 2, 0, 0, 1, 0, 2, 0, 2, 0, 2, 0, 0, 0, 1, 2, 2, 2, 0, 2,
       2, 1, 2, 0, 1, 2, 0, 2, 1, 0, 2, 1, 0, 1, 0, 1, 0, 2, 1, 2, 0, 2,
       2, 2, 0, 0, 0, 2, 0, 1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       1, 2, 1, 0, 2, 0, 2, 2, 1, 1, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 2, 0,
       2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 1, 2, 2, 0, 0, 2,
       2, 0, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 1, 2, 1, 1, 1, 1, 2,
       2, 2, 0, 0, 1, 1, 2, 2, 0, 2, 2, 2, 1, 0, 2, 1, 1, 2, 2, 1, 2, 2,
       0, 2, 0, 0, 0, 1, 2, 0, 1, 0, 1, 0, 2, 1, 2, 0, 2, 1, 0, 0, 1, 1,
       2, 1, 0, 1, 1, 0, 2, 1, 2, 1, 1, 2, 1, 0])

In [17]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_test,y_pred)
confusion_matrix(y_test,y_pred)
# print(classification_report(y_test,y_pred))
# print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

0.6


# Task
Tune the hyperparameters of the Logistic Regression model using GridSearchCV to find the best 'C' and 'solver' values. Then, train a new model with these optimal parameters, predict on the test set, and evaluate its accuracy, confusion matrix, and classification report, comparing the new accuracy with the previous one.

## Define Hyperparameter Grid

### Subtask:
Define a dictionary with hyperparameters for Logistic Regression, such as 'C' (regularization strength) and 'solver', to explore during tuning.


**Reasoning**:
I will define a dictionary `param_grid` containing the specified hyperparameters ('C' and 'solver') and their respective lists of values for Logistic Regression tuning.



In [18]:
param_grid = {
    'C': [0.1, 1, 10, 100],
    'solver': ['lbfgs', 'liblinear', 'newton-cg', 'sag', 'saga']
}
print(param_grid)

{'C': [0.1, 1, 10, 100], 'solver': ['lbfgs', 'liblinear', 'newton-cg', 'sag', 'saga']}


**Reasoning**:
Now that the hyperparameter grid is defined, the next step is to import the `GridSearchCV` class from `sklearn.model_selection` to perform an exhaustive search over the specified parameter values for the Logistic Regression model.



In [19]:
from sklearn.model_selection import GridSearchCV
print("GridSearchCV imported successfully.")

GridSearchCV imported successfully.


**Reasoning**:
To perform hyperparameter tuning, I will initialize `GridSearchCV` with a `LogisticRegression` estimator, the `param_grid` containing the hyperparameters to search, and set `cv=5` for cross-validation to find the optimal combination of parameters.



In [20]:
logreg = LogisticRegression(multi_class='ovr', solver='liblinear', max_iter=1000) # Setting solver to liblinear and max_iter for broad compatibility across C values
grid_search = GridSearchCV(logreg, param_grid, cv=5, scoring='accuracy', verbose=1, n_jobs=-1)
grid_search.fit(X_train, y_train)
print("GridSearchCV initialized and fitted.")

Fitting 5 folds for each of 20 candidates, totalling 100 fits
GridSearchCV initialized and fitted.


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


**Reasoning**:
Now that GridSearchCV has completed fitting, the next logical step is to retrieve and display the best hyperparameters and their corresponding accuracy score found during the search.



In [21]:
print(f"Best parameters: {grid_search.best_params_}")
print(f"Best cross-validation accuracy: {grid_search.best_score_:.4f}")

Best parameters: {'C': 1, 'solver': 'lbfgs'}
Best cross-validation accuracy: 0.6400


**Reasoning**:
With the best hyperparameters identified, the next step is to train a new Logistic Regression model using these optimal parameters. This model will then be used to make predictions on the test set.



In [22]:
best_lr = grid_search.best_estimator_
print(f"Best Logistic Regression model: {best_lr}")

Best Logistic Regression model: LogisticRegression(C=1, max_iter=1000, multi_class='ovr')


**Reasoning**:
Now that we have the best model from GridSearchCV, the next step is to use this `best_lr` model to make predictions on the unseen test data (`X_test`).



In [23]:
y_pred_tuned = best_lr.predict(X_test)
print(y_pred_tuned)

[0 0 0 0 2 0 2 2 2 1 0 2 1 2 2 2 2 0 2 2 0 2 2 2 0 1 1 1 0 1 0 1 2 0 0 1 2
 0 2 0 2 0 0 1 0 0 0 2 1 2 1 0 2 1 1 0 0 0 0 0 0 2 1 2 0 2 2 0 2 2 0 2 2 0
 0 1 2 2 0 2 2 2 0 1 0 1 0 1 2 0 2 2 0 0 1 0 2 0 2 0 2 0 0 0 1 2 2 2 0 2 2
 1 2 0 1 2 0 2 1 0 2 1 0 1 0 1 0 2 1 2 0 2 2 2 0 0 0 2 0 1 2 2 2 2 0 2 2 2
 0 0 1 0 1 0 0 0 0 1 0 2 2 0 2 2 2 0 0 0 0 2 1 0 0 0 2 2 1 2 1 0 2 0 2 2 1
 1 1 2 0 0 0 1 0 1 2 0 2 0 2 0 0 0 2 2 2 2 2 2 2 2 1 0 2 2 1 2 2 0 0 2 2 0
 2 2 0 2 2 2 0 2 2 0 0 2 0 1 2 1 1 1 1 2 2 2 0 0 1 1 2 2 0 2 2 2 1 0 2 1 1
 2 2 1 2 2 0 2 0 0 0 1 2 0 1 0 1 0 2 1 2 0 2 1 0 0 1 1 2 1 0 1 1 0 2 1 2 1
 1 2 1 0]


**Reasoning**:
Now that predictions from the tuned model (`y_pred_tuned`) are available, the next logical step is to evaluate its performance by calculating the accuracy score against the true test labels (`y_test`).



In [24]:
tuned_accuracy = accuracy_score(y_test, y_pred_tuned)
print(f"Tuned Model Accuracy: {tuned_accuracy:.4f}")

Tuned Model Accuracy: 0.6000


**Reasoning**:
With the tuned model's predictions, the next step is to evaluate its performance more comprehensively by generating and printing the confusion matrix, which provides a detailed breakdown of correct and incorrect classifications for each class.



In [25]:
tuned_confusion_matrix = confusion_matrix(y_test, y_pred_tuned)
print("Tuned Model Confusion Matrix:")
print(tuned_confusion_matrix)

Tuned Model Confusion Matrix:
[[67 26  6]
 [38 27 31]
 [ 6 13 86]]


**Reasoning**:
To get a more detailed evaluation of the tuned model's performance, I will generate and print the classification report, which includes precision, recall, and F1-score for each class.



In [26]:
tuned_classification_report = classification_report(y_test, y_pred_tuned)
print("Tuned Model Classification Report:")
print(tuned_classification_report)

Tuned Model Classification Report:
              precision    recall  f1-score   support

           0       0.60      0.68      0.64        99
           1       0.41      0.28      0.33        96
           2       0.70      0.82      0.75       105

    accuracy                           0.60       300
   macro avg       0.57      0.59      0.58       300
weighted avg       0.57      0.60      0.58       300



**Reasoning**:
All evaluation metrics for the tuned model have been generated. The final step of the task is to compare the accuracy of the tuned model with the initial model and then mark the subtask as complete.



In [27]:
print(f"Initial Model Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"Tuned Model Accuracy: {tuned_accuracy:.4f}")

if tuned_accuracy > accuracy_score(y_test, y_pred):
    print("The tuned model has a higher accuracy.")
elif tuned_accuracy < accuracy_score(y_test, y_pred):
    print("The tuned model has a lower accuracy.")
else:
    print("The tuned model has the same accuracy as the initial model.")

Initial Model Accuracy: 0.6000
Tuned Model Accuracy: 0.6000
The tuned model has the same accuracy as the initial model.
